name: Docker Image CI

on:
    release:
      types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg VERSION=$GITHUB_REF_NAME --tag "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:$(date +%s)" --tag "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:$GITHUB_REF_NAME" --tag "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest"
    - name: Login to the Docker Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    - name: Publish the Docker image
      run: docker push --all-tags --tag "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}"
